name: base
description: Base application for simplism

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^1.3.1
  local_auth: ^2.1.3
  font_awesome_flutter: ^10.3.0
  flutter_dotenv: ^5.0.2
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.16
  provider: ^6.0.5
  image_picker: ^0.8.6
  email_validator: ^2.1.16
  system_theme: ^2.1.0
  flutter_native_splash: ^2.2.16
  cupertino_icons: ^1.0.5
  circle_flags: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/i18n/en.json
    - assets/i18n/nl.json
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSansExtraBold
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
