name: base
description: Base application for simplism

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^1.5.0
  local_auth: ^2.1.6
  font_awesome_flutter: ^10.4.0
  flutter_dotenv: ^5.0.2
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.18
  provider: ^6.0.5
  image_picker: ^0.8.7
  email_validator: ^2.1.16
  system_theme: ^2.1.0
  flutter_native_splash: ^2.2.16
  cupertino_icons: ^1.0.5
  circle_flags: ^1.0.4
  flutter_html: ^3.0.0-alpha.6
  file_picker: ^5.2.5
  quill_html_editor: ^2.1.5
  flutter_widget_from_html: ^0.10.0
  url_launcher: ^6.1.10
  jiffy: ^5.0.0
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  path_provider: ^2.0.13

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/i18n/en.json
    - assets/i18n/nl.json
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSansExtraBold
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
